/*
  Auto-generated by Spline
*/
import * as THREE from 'three';
import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/mBCKON2lCzKy-DIH/scene.splinecode')
  const mergedGeometry = THREE.BufferGeometryUtils.merge(geometry1, geometry2);

  return (
    <>
      <color attach="background" args={['#3a3a45']} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <pointLight
            name="Point Light"
            castShadow
            intensity={1}
            decay={0.75}
            distance={2000}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={100}
            shadow-camera-far={100000}
            position={[-658.56, -562.5, 223.07]}
          />
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={4}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-4000}
            shadow-camera-right={4000}
            shadow-camera-top={4000}
            shadow-camera-bottom={-4000}
            position={[-711.78, 518.8, 300]}
          />
          <mesh
            name="Base shape"
            geometry={nodes['Base shape'].geometry}
            material={materials['Glass  dark']}
            visible={false}
            castShadow
            receiveShadow
            rotation={[Math.PI / 2, 0, 0]}
          />
          <OrthographicCamera name="1" makeDefault={true} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={2} color="#fefefe" />
        </scene>
      </group>
    </>
  )
}
